import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import Navigation from "./component/Navigation/Navigation";
import Footer from "./component/Footer/Footer";


const Urbanist_ = Urbanist({ 
subsets: ["latin"],
weight:['100','200','300','400','500','600','700','800','900'],
variable:'--font-urbanist'
});

export const metadata: Metadata = {
  title: "Ringtonz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={Urbanist_.className}>
        {children}</body>
    </html>
  );
}
